export const FETCHING_POKEMONS = "FETCHING_POKEMONS"
export const RESOLVING_POKEMONS = "RESOLVING_POKEMONS "
export const REJECTING_POKEMONS = "REJECTING_POKEMONS"

export const NEXTPAGE_POKEMONS = "NEXTPAGE_POKEMONS"
export const PREVIOUS_PAGE_POKEMONS = "REVIOUS_PAGE_POKEMONS"

export const FETCHING_POKEMON_DETAIL = "FETCHING_POKEMON_DETAIL"
export const RESOLVING_POKEMONS_DETAIL = "RESOLVING_POKEMONS_DETAIL"
export const REJECTING_POKEMONS_DETAIL= " REJECTING_POKEMONS_DETAIL"